name: Auto Issues

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

permissions:
  issues: write

jobs:
  create_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Create 500 issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          printf -v v \\x$(printf %x $((97 + $(date -u +%H)/2)))
          if [[ "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]]; then
            v="x"
          fi
          for i in $(seq 1 500); do
            gh issue create \
              --title "issue #${i}${v} for $(date "+%F")" \
              --body "wow thats a lot of issues" \
              --repo "${{ github.repository }}"
            echo "Created issue #${i}${v}"
            sleep 1
          done
