name: Auto Issues

on:
  schedule:
    - cron: '0 0,6,12,18 * * *'
  workflow_dispatch:

permissions:
  issues: write

jobs:
  create_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Create 500 issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          t=$(date -u +%H)
          if   [[ "$t" == "00" ]]; then v="a"
          elif [[ "$t" == "06" ]]; then v="b"
          elif [[ "$t" == "12" ]]; then v="c"
          elif [[ "$t" == "18" ]]; then v="d"
          else                          v="x"; fi          
          for i in $(seq 1 500); do
            gh issue create \
              --title "issue #${i}${v} for $(date "+%F")" \
              --body "wow thats a lot of issues" \
              --repo "${{ github.repository }}"
            echo "Created issue #${i}${v}"
            sleep 1
          done
